[phases.setup]
nixPkgs = ["php82", "composer", "nodejs-18_x"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash scripts/start.sh"

